[project]
name = "dagshub-mlops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dagshub>=0.5.10",
    "dvc>=3.60.1",
    "dvc-s3>=3.2.2",
    "mlflow>=3.1.1",
    "scikit-learn>=1.7.0",
]
